apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nettools
  name: nettools
spec:
  containers:
  - image: burlyluo/nettoolbox
    name: nettools
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: k8s-node-01
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nettools2
  name: nettools2
spec:
  containers:
  - image: burlyluo/nettoolbox
    name: nettools2
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: k8s-node-01
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nettools3
  name: nettools3
spec:
  containers:
  - image: burlyluo/nettoolbox
    name: nettools3
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: k8s-node-02
